site_name: KOSMOS
nav:
    - Assembly:
        - Assembly guide: index.md
    - Dummy:
        - Dummy: dummy.md
   
    
theme:
    name: readthedocs

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
