site_name: KOSMOS
nav:
    - Setup:
       
    - Assembly:
        - Assembly guide: assembly_guide.md
    - Usage:
        -
    - Hardware:
        
    - Under the hood:
        
    - Changelog:
        - 
    - Contribute:
       
    - About:
    
theme:
    name: readthedocs

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
