site_name: KOSMOS
nav:
    - Fabrication :
        - Fournitures: materials_fr.md
        - Matériel: tools_fr.md
        - Guide d'assemblage: assembly-guide_fr.md
        - Annexes: annex_fr.md 
        
    - Utilisation en mer :
        - Check-list: check-list_fr.md
        - Guide de déploiement: deployment.md
        - Retour à terre: landing.md
        
theme:
    name: material
    palette:
      primary: blue

plugins:
  - search
  - i18n:
      default_language: fr
      languages:
        fr: Français
        en: English

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
