site_name: KOSMOS
nav:
    - Fabrication :
        - Fournitures: materials_fr.md
        - Matériel: tools_fr.md
        - Guide d'assemblage: assembly-guide_fr.md
        - Annexes: annexe_fr.md 
    - Dummy:
        - Dummy: dummy.md
   
    
theme:
    name: readthedocs

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
