site_name: KOSMOS
nav:
    - I/ Fabrication :
        - 1. Fournitures: materials_fr.md
        - 2. Matériel: tools_fr.md
        - 3. Fabrications des piéces: productions_of_parts_fr.md
        - 4. Guide d'assemblage: assembly-guide_fr.md
        - 5. Installation du software: software_install_fr.md
        - 6. Calibration du temps de pause: calibrate_fr.md
        - 7. Annexes:
          - Fabrication d'un PCB: make_a_PCB_fr.md 

    - II/ Usage en mer :
        - 1. Check-list: check-list_fr.md
        - 2. Guide de déploiement: deployment.md
        - 3. Retour à terre: landing.md
    
    - III/ Collecte et gestion des données :
        - 1. Correction des images: image-processing_fr.md
    
    - IV/ Contribuer : 
        - 1. Editer cette documentation: edit-this-doc_fr.md
        
    - A propos :
        - Licence : license.md
        
theme:
    name: material
    palette:
      primary: blue

plugins:
  - search
  - i18n:
      default_language: fr
      languages:
        fr: Français
        en: English

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true

formats:
    - pdf
    - epub
