site_name: KOSMOS
nav:
    - I/ Fabrication :
        - 1. Fournitures: materials_fr.md
        - 2. Matériel: tools_fr.md
        - 3. Guide d'assemblage: assembly-guide_fr.md
        - 4. Annexes: annex_fr.md 
        
    - II/ Utilisation en mer :
        - 1. Check-list: check-list_fr.md
        - 2. Guide de déploiement: deployment.md
        - 3. Retour à terre: landing.md
        
theme:
    name: material
    palette:
      primary: blue

plugins:
  - search
  - i18n:
      default_language: fr
      languages:
        fr: Français
        en: English

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
